server:
  port: 8083
spring:
  application:
    name: UserService
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 6000
      client-type: lettuce
      connect-timeout: 3000
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
      use-key-prefix: true
